# Generated by Django 2.0.7 on 2021-01-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskill',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='parent',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skill',
            field=models.ManyToManyField(to='user_profile.UserSkill'),
        ),
    ]
