# Generated by Django 2.2.17 on 2021-01-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20210129_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_image.png', null=True, upload_to=''),
        ),
    ]
